import os

MONGO_HOST = os.getenv('MONGO_HOST')
MONGO_PORT = int(os.getenv('MONGO_PORT'))
MONGO_DB_NAME = os.getenv('MONGO_INITDB_DATABASE')
MONGO_USERNAME = os.getenv('MONGO_INITDB_ROOT_USERNAME')
MONGO_PASSWORD = os.getenv('MONGO_INITDB_ROOT_PASSWORD')

MONGO_CONNECTION_STRING = f'mongodb://{MONGO_USERNAME}:{MONGO_PASSWORD}@{MONGO_HOST}:{MONGO_PORT}'

TRADE_MARK_COLLECTION = os.getenv('TRADE_MARK_COLLECTION')
PARSED_FILE_COLLECTION = os.getenv('PARSED_FILE_COLLECTION')

FTP_HOST = os.getenv('FTP_HOST')
FTP_USERNAME = os.getenv('FTP_USERNAME')
FTP_PASSWORD = os.getenv('FTP_PASSWORD')
FTP_ROOT_FOLDER = os.getenv('FTP_ROOT_FOLDER')
